---
- name: creates ansible cache path
  file: path="{{ ansible_cache_path }}" state=directory

- name: downloads kafka
  get_url:
    url: http://ftp.unicamp.br/pub/apache/kafka/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz
    dest: "{{ ansible_cache_path }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"

- name: extracts kafka
  unarchive:
    src: "{{ ansible_cache_path }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"
    dest: /usr/local
    creates: /usr/local/kafka_{{ kafka_scala_version }}-{{ kafka_version }}"

- name: creates kafka link
  file:
    src: "/usr/local/kafka_{{ kafka_scala_version }}-{{ kafka_version }}"
    dest: /usr/local/kafka
    state: link